# Generated by Django 5.2.4 on 2026-02-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
