# Generated by Django 5.2.4 on 2026-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_behaviorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
